version: '3'
services:
  jmeter-service:
    build:
      context: ./jmeter-service/
      args:
        serviceImageVersion: ${SERVICE_IMAGE_VERSION}
    image: eventuateexamples/eventuate-tram-examples-customers-and-orders-jmeter-service:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - customer-service
    ports:
      - "8084:8080"
    environment:
      JMETER_SERVICE_RESULTS_FOLDER: /usr/local/results
      JMETER_SERVICE_TESTPLAN_PATH: /usr/local/plans/TestPlan.jmx
      JMETER_PATH: /usr/local/apache-jmeter-5.2.1/bin/jmeter
