apiVersion: v1
kind: Service
metadata:
  name: cdc-service
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    svc: cdc-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-service
  namespace: eventuate-tram-examples-customers-and-orders
  labels:
    svc: cdc-service
spec:
  selector:
    matchLabels:
      svc: cdc-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: cdc-service
    spec:
      containers:
      - name: cdc-service
        image: eventuateio/eventuate-cdc-service:0.6.1.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: httpport
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: sql-config
                key: connection_string
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: sql-config
                key: sql_user
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: sql-config
                key: sql_password
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            valueFrom:
              configMapKeyRef:
                name: sql-config
                key: sql_driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: kafka-service:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: zookeeper:2181
          - name: SPRING_DATASOURCE_TEST_ON_BORROW
            value: "true"
          - name: SPRING_DATASOURCE_VALIDATION_QUERY
            value: SELECT 1
          - name: EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS
            value: "500"
          - name: EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING
            value: "1000"
          - name: EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING
            value: "100"
          - name: EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS
            value: "500"
          - name: EVENTUATELOCAL_CDC_READER_NAME
            value: MssqlPollingReader
          - name: SPRING_PROFILES_ACTIVE
            value: EventuatePolling
          - name: JAVA_OPTS
            value: "-Xmx64m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 25
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 25
---