apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:3.0.4
        command: ["mongod", "--smallfiles"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: "/data/db"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      namespace: eventuate-tram-examples-customers-and-orders
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 256Mi
---