apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: eventuate-tram-examples-customers-and-orders
  labels:
    name: zookeeper
spec:
  ports:
  - port: 2181
    targetPort: 2181
  type: LoadBalancer
  selector:
    role: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  selector:
    matchLabels:
      role: zookeeper
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        role: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: zookeeper
          image: eventuateio/eventuate-zookeeper:${EVENTUATE_COMMON_VERSION?}
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          livenessProbe:
            exec:
              command:
              - echo
              - ruok |
              - nc
              - localhost
              - "2181"
            periodSeconds: 10
            failureThreshold: 25
          readinessProbe:
            exec:
              command:
              - echo
              - ruok |
              - nc
              - localhost
              - "2181"
            periodSeconds: 10
            failureThreshold: 25
          volumeMounts:
            - name: zookeeper-persistent-storage
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-persistent-storage
      namespace: eventuate-tram-examples-customers-and-orders
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Mi
---
